baseURL = 'https://dmgiangi.dev/'
languageCode = 'en-us'
title = 'Portfolio'
paginate = 5

[params]
contentTypeName = "posts"
showMenuItems = 3
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
autoCover = false
showLastUpdated = true
enableGitInfo = true
readingTime = true
Toc = false
TocTitle = "Table of Contents"

[languages]
[languages.en]
languageName = "English"
title = "Terminal"

[languages.en.params]
subtitle = "A simple, retro theme for Hugo"
owner = "Gianluigi De Marco"
keywords = ""
copyright = ""
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "Gianluigi De Marco"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About Me"
url = "/about"

[module]
[[module.imports]]
path = 'terminal'