services:
  portfolio:
    image: ghcr.io/dmgiangi/portfolio:latest
    ports:
      - "8080:80"
    restart: always
    pull_policy: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${DOMAIN_ROOT}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"